import { describe, expect, test } from 'vitest'
import openapiRaw from './openapi.json?raw'
import schemaRaw from './schema.d.ts?raw'

/** Re-serialize the way scripts/dump_openapi.py does: sorted keys, 2-space indent, LF. */
function canonical(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonical)
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.keys(value)
        .sort()
        .map((k) => [k, canonical((value as Record<string, unknown>)[k])]),
    )
  }
  return value
}

describe('generated client artifacts (R9: regenerated, never hand-edited)', () => {
  const openapi = JSON.parse(openapiRaw) as { paths: Record<string, unknown> }

  test('openapi.json uses LF only, so it does not churn between Windows and Unix machines', () => {
    expect(openapiRaw.includes('\r')).toBe(false)
    expect(schemaRaw.includes('\r')).toBe(false)
  })

  test('openapi.json is exactly what dump_openapi.py writes (sorted keys, no hand edits)', () => {
    expect(openapiRaw).toBe(JSON.stringify(canonical(openapi), null, 2) + '\n')
  })

  test('schema.d.ts covers exactly the paths in openapi.json (both halves regenerated together)', () => {
    const typedPaths = [...schemaRaw.matchAll(/^ {4}"(\/[^"]*)": \{$/gm)].map((m) => m[1])
    expect(typedPaths.sort()).toEqual(Object.keys(openapi.paths).sort())
  })

  test('schema.d.ts still carries the openapi-typescript banner (not a hand-written file)', () => {
    expect(
      schemaRaw.startsWith('/**\n * This file was auto-generated by openapi-typescript.'),
    ).toBe(true)
  })
})

describe('source rules', () => {
  const sources = import.meta.glob<string>(['../**/*.{ts,tsx}', '!../**/*.test.{ts,tsx}'], {
    query: '?raw',
    import: 'default',
    eager: true,
  })
  // Comments are stripped first: they legitimately name what the rules forbid.
  const stripComments = (src: string) =>
    src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:])\/\/.*$/gm, '$1')
  const files = Object.entries(sources)
    .filter(([path]) => !path.endsWith('schema.d.ts'))
    .map(([path, src]) => [path, stripComments(src)] as const)

  test('the scan actually sees the app source', () => {
    expect(files.length).toBeGreaterThan(10)
  })

  test('rule 14: no raw fetch() anywhere - every call goes through the generated client', () => {
    const offenders = files.filter(([, src]) => /(^|[^.\w])fetch\s*\(/m.test(src))
    expect(offenders.map(([path]) => path)).toEqual([])
  })

  test('Part 7.3: no hand-written `any` types', () => {
    const offenders = files.filter(([, src]) => /(:\s*any\b|\bas\s+any\b|<any>)/.test(src))
    expect(offenders.map(([path]) => path)).toEqual([])
  })

  test('rule 13: nothing touches browser storage or cookies', () => {
    const offenders = files.filter(([, src]) =>
      /\b(localStorage|sessionStorage|indexedDB)\b|document\.cookie/.test(src),
    )
    expect(offenders.map(([path]) => path)).toEqual([])
  })
})
