/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/disposition-signoffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Disposition Signoffs
         * @description Global feed across every project - History screen (E6 screen 6). Same resolution
         *     as get_all_events above.
         */
        get: operations["get_all_disposition_signoffs_disposition_signoffs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Events
         * @description Global feed across every project - History screen (E6 screen 6). CONTRACT_CHANGES.md
         *     2026-09-26 "Routers registered; P2.8's storage routes differ from Part 5.6" - added
         *     alongside the per-project route above, not instead of it.
         */
        get: operations["get_all_events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Lot */
        post: operations["upload_lot_lots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Demo Lot
         * @description E7 step 2: a synthetic demo lot, so the system is demonstrable without a file on hand.
         *     A fresh lot_id per call (so repeat clicks don't collide); the generator's own seed/family
         *     defaults otherwise, so the demo lot is deterministic given that lot_id (AGENTS.md rule 9).
         */
        post: operations["load_demo_lot_lots_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lot Summary */
        get: operations["get_lot_summary_lots__lot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/checkpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Checkpoint */
        post: operations["upload_checkpoint_lots__lot_id__checkpoints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/dpa-work-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Dpa Work Order
         * @description E13 step 5: up to 3 recommended parts for destructive physical analysis, on a COMPLETE lot
         *     only (a lot still IN_PROGRESS has no final verdict tier to select against - 409, not a guess).
         */
        post: operations["create_dpa_work_order_lots__lot_id__dpa_work_order_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quality Flags
         * @description E7 step 7, surfaced separately from `LotUploadResponse` - that response model is frozen
         *     (`contracts.py`) with no field for quality flags; logged in CONTRACT_CHANGES.md rather than
         *     hand-edited. Not a contract type itself, so no `response_model` - plain JSON.
         */
        get: operations["get_quality_flags_lots__lot_id__quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Report */
        post: operations["generate_report_lots__lot_id__report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parts/{component_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Part Detail */
        get: operations["get_part_detail_parts__component_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parts/{component_id}/confirmed-outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Confirmed Outcome
         * @description E13 step 1: records a confirmed real-world outcome for a part, linked to the analysis_run_id
         *     of the latest stored run containing it (never the disposition itself - this measures whether the
         *     model's verdict tier was right, a different question from whether the human's disposition was).
         *     Append-only: never touches disposition_signoffs. No event is logged - see CONTRACT_CHANGES.md,
         *     this block: none of the five event_type literal values fits this action, and AGENTS.md rule 3
         *     forbids inventing a new one here.
         */
        post: operations["create_confirmed_outcome_parts__component_id__confirmed_outcome_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parts/{component_id}/disposition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Disposition */
        post: operations["create_disposition_parts__component_id__disposition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/disposition-signoffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Disposition Signoffs */
        get: operations["get_disposition_signoffs_projects__project_id__disposition_signoffs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Events */
        get: operations["get_project_events_projects__project_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/corrective-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Corrective Status
         * @description E13 steps 6-8: live-computed on every call, nothing stored, nothing to dismiss. The ceiling
         *     read here is the live Settings value (post dual sign-off), via identity.router's own state
         *     function - never re-derived from raw events a second time.
         */
        get: operations["get_corrective_status_settings_corrective_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose Setting */
        post: operations["propose_setting_settings_propose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/signoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signoff Setting */
        post: operations["signoff_setting_settings_signoff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/worklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Worklist
         * @description E13 step 4: "N dispositions awaiting a confirmed outcome" - tracking only, changes nothing.
         */
        get: operations["get_worklist_settings_worklist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_load_demo_lot_lots_demo_post */
        Body_load_demo_lot_lots_demo_post: {
            /** Account Id */
            account_id: string;
        };
        /** Body_upload_checkpoint_lots__lot_id__checkpoints_post */
        Body_upload_checkpoint_lots__lot_id__checkpoints_post: {
            /** Account Id */
            account_id: string;
            /** File */
            file: string;
            /** Reference Expected Json */
            reference_expected_json?: string | null;
        };
        /** Body_upload_lot_lots_post */
        Body_upload_lot_lots_post: {
            /** Account Id */
            account_id: string;
            /** Date Code */
            date_code: string;
            /** File */
            file: string;
            /** Lot Id */
            lot_id: string;
            /** Manufacturer */
            manufacturer: string;
            /** Part Number */
            part_number: string;
            /** Reference Expected Json */
            reference_expected_json?: string | null;
            /** Test Date */
            test_date?: string | null;
        };
        /** ConfirmedOutcomeRecord */
        ConfirmedOutcomeRecord: {
            /** Account Id */
            account_id: string;
            /** Analysis Run Id */
            analysis_run_id: string;
            /** Component Id */
            component_id: string;
            /**
             * Confirmed Outcome
             * @enum {string}
             */
            confirmed_outcome: "Confirmed Good" | "Confirmed Defective" | "Unknown";
            /** Note */
            note: string | null;
            /** Project Id */
            project_id: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
        };
        /** ConfirmedOutcomeRequest */
        ConfirmedOutcomeRequest: {
            /**
             * Confirmed Outcome
             * @enum {string}
             */
            confirmed_outcome: "Confirmed Good" | "Confirmed Defective" | "Unknown";
            /** Note */
            note?: string | null;
        };
        /** CorrectiveStatusResponse */
        CorrectiveStatusResponse: {
            /** Confirmed Outcome Count */
            confirmed_outcome_count: number;
            /** Fn Rate */
            fn_rate?: number | null;
            /** Fp Rate */
            fp_rate?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "OK" | "CEILING_EXCEEDED" | "INSUFFICIENT_DATA";
        };
        /** DPARecommendation */
        DPARecommendation: {
            /** Component Id */
            component_id: string;
            /** Reason */
            reason: string;
        };
        /** DPAWorkOrderResponse */
        DPAWorkOrderResponse: {
            /** Recommendations */
            recommendations: components["schemas"]["DPARecommendation"][];
        };
        /** DispositionRecord */
        DispositionRecord: {
            /** Account Id */
            account_id: string;
            /** Analysis Run Id */
            analysis_run_id: string;
            /** Component Id */
            component_id: string;
            /** Project Id */
            project_id: string;
            /** Rationale */
            rationale: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "ACCEPT" | "HOLD" | "REJECT";
        };
        /** DispositionRequest */
        DispositionRequest: {
            /** Rationale */
            rationale: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "ACCEPT" | "HOLD" | "REJECT";
        };
        /** EcodDimensionRow */
        EcodDimensionRow: {
            /** Dimension */
            dimension: string;
            /** Score */
            score: number;
        };
        /** EventResponse */
        EventResponse: {
            /** Account Id */
            account_id: string;
            /** Event Id */
            event_id: string;
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "ingest" | "checkpoint_add" | "analysis_run" | "config_change" | "timing_flag";
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Project Id */
            project_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Account Id */
            account_id: string;
            /** Pin */
            pin: string;
        };
        /** LotDisposition */
        LotDisposition: {
            /** Is Forecast */
            is_forecast: boolean;
            /** Lot Id */
            lot_id: string;
            /** Pda Result */
            pda_result: number;
            /**
             * Status
             * @enum {string}
             */
            status: "IN_PROGRESS" | "COMPLETE";
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "LOT_ON_TRACK" | "LOT_AT_RISK" | "STOP_RUN_RECOMMENDED" | "ACCEPT" | "HOLD" | "REJECT";
        };
        /** LotSummaryResponse */
        LotSummaryResponse: {
            /** Assessments */
            assessments: components["schemas"]["RiskAssessment"][];
            disposition: components["schemas"]["LotDisposition"];
            /**
             * Explanation Summary
             * @default
             */
            explanation_summary: string;
            /**
             * Insufficient Data Components
             * @default []
             */
            insufficient_data_components: string[];
            /**
             * Module A Results
             * @default {}
             */
            module_a_results: {
                [key: string]: components["schemas"]["ModuleAResult"];
            };
            /**
             * Module B Results
             * @default {}
             */
            module_b_results: {
                [key: string]: components["schemas"]["ModuleBResult"];
            };
            /**
             * Part Explanations
             * @default {}
             */
            part_explanations: {
                [key: string]: components["schemas"]["PartExplanation"];
            };
        };
        /** LotUploadResponse */
        LotUploadResponse: {
            /**
             * Insufficient Data Components
             * @default []
             */
            insufficient_data_components: string[];
            /** Lot Id */
            lot_id: string;
            /** Part Number */
            part_number: string;
            /** Reading Count */
            reading_count: number;
            /**
             * Status
             * @enum {string}
             */
            status: "IN_PROGRESS" | "COMPLETE";
        };
        /** MCDContributionRow */
        MCDContributionRow: {
            /** Contribution */
            contribution: number;
            /** Parameter */
            parameter: string;
        };
        /** ModuleAResult */
        ModuleAResult: {
            /** Combined Severity */
            combined_severity: number;
            /** Component Id */
            component_id: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "above_median" | "below_median";
            /** Ecod Score */
            ecod_score: number;
            /** Explainable Corroboration */
            explainable_corroboration: boolean;
            /** Explainable Tags */
            explainable_tags: {
                [key: string]: boolean;
            };
            /** Isolation Forest Score */
            isolation_forest_score: number | null;
            /** Lot Id */
            lot_id: string;
            /** Mcd Distance */
            mcd_distance: number | null;
            /** Parameter */
            parameter: string;
            /** Robust Z */
            robust_z: number;
            /** Severity Cap Reason */
            severity_cap_reason: string | null;
            /**
             * Severity Tier
             * @enum {string}
             */
            severity_tier: "PASS" | "REVIEW" | "REJECT";
        };
        /** ModuleBResult */
        ModuleBResult: {
            /** Component Id */
            component_id: string;
            /** Drift Rate */
            drift_rate: number | null;
            /** Exceeds Safety Slope */
            exceeds_safety_slope: boolean | null;
            /** Forecast Unavailable */
            forecast_unavailable: boolean;
            /** Interval Lower */
            interval_lower: number | null;
            /** Interval Upper */
            interval_upper: number | null;
            /** Lot Id */
            lot_id: string;
            /** Lower Bound Exceeds Safety Slope */
            lower_bound_exceeds_safety_slope: boolean | null;
            /** Parameter */
            parameter: string;
            /** Physics Baseline Prediction */
            physics_baseline_prediction: number | null;
            /** Physics Disagreement Gap */
            physics_disagreement_gap: number | null;
            /** Predicted 168H */
            predicted_168h: number | null;
            /** Safety Slope */
            safety_slope: number | null;
        };
        /** PartDetailResponse */
        PartDetailResponse: {
            /** Analysis Run Id */
            analysis_run_id?: string | null;
            /** Component Id */
            component_id?: string | null;
            /** Confidence Qualifier */
            confidence_qualifier: string;
            /** Confirmed Outcomes */
            confirmed_outcomes: components["schemas"]["ConfirmedOutcomeRecord"][];
            /** Disposition History */
            disposition_history: components["schemas"]["DispositionRecord"][];
            explanation?: components["schemas"]["PartExplanation"] | null;
            /** Explanation Sentence */
            explanation_sentence: string;
            /** Lot Id */
            lot_id?: string | null;
            module_a?: components["schemas"]["ModuleAResult"] | null;
            module_b?: components["schemas"]["ModuleBResult"] | null;
            /** Project Id */
            project_id?: string | null;
            /** Severity Cap Note */
            severity_cap_note: string | null;
            /** Staleness Note */
            staleness_note: string | null;
            /** Unavailable Forecast Note */
            unavailable_forecast_note: string | null;
            /** Verdict */
            verdict?: ("PASS" | "WATCH" | "REJECT") | null;
        };
        /**
         * PartExplanation
         * @description Per-component explainability payload (E4 steps 1-9): the four chart mechanisms plus the
         *     text/notes for that one part. Every field optional/defaulted - a PASS part gets none of this
         *     (AnalysisResults.part_explanations only ever holds non-PASS parts, Part 3g).
         */
        PartExplanation: {
            /** Confidence Qualifier */
            confidence_qualifier?: string | null;
            /**
             * Ecod Dimensions
             * @default []
             */
            ecod_dimensions: components["schemas"]["EcodDimensionRow"][];
            /** Explanation Sentence */
            explanation_sentence?: string | null;
            /**
             * Mcd Contributions
             * @default []
             */
            mcd_contributions: components["schemas"]["MCDContributionRow"][];
            /** Severity Cap Note */
            severity_cap_note?: string | null;
            /**
             * Shap Contributions
             * @default []
             */
            shap_contributions: components["schemas"]["ShapContributionRow"][];
            /**
             * Trajectory
             * @default []
             */
            trajectory: components["schemas"]["TrajectoryPoint"][];
            /** Unavailable Forecast Note */
            unavailable_forecast_note?: string | null;
            /**
             * Zscore Table
             * @default []
             */
            zscore_table: components["schemas"]["ZScoreTableRow"][];
        };
        /** PendingSettingChange */
        PendingSettingChange: {
            /**
             * Field
             * @enum {string}
             */
            field: "fn_fp_cost_ratio" | "pda_threshold" | "confirmed_outcome_fn_ceiling";
            /** Proposed By */
            proposed_by: string;
            /** Proposed Value */
            proposed_value: number;
            /** Signed Off By */
            signed_off_by: string | null;
        };
        /** ProjectSummary */
        ProjectSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Date Code */
            date_code?: string | null;
            /** Lot Id */
            lot_id: string;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Part Number */
            part_number: string;
            /** Project Id */
            project_id: string;
            /** Test Date */
            test_date?: string | null;
        };
        /** RiskAssessment */
        RiskAssessment: {
            /** Actual 168H */
            actual_168h: number | null;
            /** Component Id */
            component_id: string;
            /** Explanation Sentence */
            explanation_sentence: string | null;
            /** Lot Id */
            lot_id: string;
            /** Module A Ran */
            module_a_ran: boolean;
            /** Module A Rank */
            module_a_rank: number;
            /** Module B Ran */
            module_b_ran: boolean;
            /** Module B Rank */
            module_b_rank: number;
            /** Predicted 168H */
            predicted_168h: number | null;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "PASS" | "WATCH" | "REJECT";
            /** Worst Parameter */
            worst_parameter: string;
        };
        /** SettingsProposalRequest */
        SettingsProposalRequest: {
            /**
             * Field
             * @enum {string}
             */
            field: "fn_fp_cost_ratio" | "pda_threshold" | "confirmed_outcome_fn_ceiling";
            /** Proposed Value */
            proposed_value: number;
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Confirmed Outcome Fn Ceiling */
            confirmed_outcome_fn_ceiling: number;
            /** Fn Fp Cost Ratio */
            fn_fp_cost_ratio: number;
            /** Pda Threshold */
            pda_threshold: number;
            /** Pending Changes */
            pending_changes: components["schemas"]["PendingSettingChange"][];
        };
        /** SettingsSignoffRequest */
        SettingsSignoffRequest: {
            /**
             * Field
             * @enum {string}
             */
            field: "fn_fp_cost_ratio" | "pda_threshold" | "confirmed_outcome_fn_ceiling";
        };
        /** ShapContributionRow */
        ShapContributionRow: {
            /** Feature */
            feature: string;
            /** Shap Value */
            shap_value: number;
            /** Value */
            value?: number | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Account Id */
            account_id: string;
            /** Role */
            role: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /**
         * TrajectoryPoint
         * @description Block 4c Part 3b: one measured checkpoint of a part's worst parameter over burn-in - built at
         *     analysis time from the stored FeatureFrame, one point per checkpoint that actually has a value
         *     (never a guessed/NaN one - rule 7, and the same discipline the earlier SHAP null bug required).
         */
        TrajectoryPoint: {
            /** Checkpoint Hour */
            checkpoint_hour: number;
            /** Lot Median */
            lot_median?: number | null;
            /** Value */
            value: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorklistResponse */
        WorklistResponse: {
            /** Pending */
            pending: components["schemas"]["DispositionRecord"][];
        };
        /** ZScoreTableRow */
        ZScoreTableRow: {
            /** Lot Median */
            lot_median: number;
            /** Parameter */
            parameter: string;
            /** Value */
            value: number;
            /** Z */
            z: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_disposition_signoffs_disposition_signoffs_get: {
        parameters: {
            query?: {
                component_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispositionRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_events_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"][];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    upload_lot_lots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_lot_lots_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_demo_lot_lots_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_load_demo_lot_lots_demo_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lot_summary_lots__lot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_checkpoint_lots__lot_id__checkpoints_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_checkpoint_lots__lot_id__checkpoints_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_dpa_work_order_lots__lot_id__dpa_work_order_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DPAWorkOrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quality_flags_lots__lot_id__quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_report_lots__lot_id__report_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_part_detail_parts__component_id__get: {
        parameters: {
            query?: {
                lot_id?: string | null;
            };
            header?: never;
            path: {
                component_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_confirmed_outcome_parts__component_id__confirmed_outcome_post: {
        parameters: {
            query?: {
                lot_id?: string | null;
            };
            header?: never;
            path: {
                component_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmedOutcomeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmedOutcomeRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_disposition_parts__component_id__disposition_post: {
        parameters: {
            query: {
                project_id: string;
                analysis_run_id: string;
            };
            header?: never;
            path: {
                component_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DispositionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispositionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    get_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_disposition_signoffs_projects__project_id__disposition_signoffs_get: {
        parameters: {
            query?: {
                component_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispositionRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_events_projects__project_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    get_corrective_status_settings_corrective_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrectiveStatusResponse"];
                };
            };
        };
    };
    propose_setting_settings_propose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsProposalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingSettingChange"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signoff_setting_settings_signoff_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsSignoffRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_worklist_settings_worklist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorklistResponse"];
                };
            };
        };
    };
}
