"""Session I2a: render docs/evidence_data/adoption/calibration_summary.md from calibration_n*.json and gaussian_null.json."""
import json
from pathlib import Path

D = Path("docs/evidence_data/adoption")
SIZES = (15, 20, 30, 40, 50, 60, 77, 100, 150)
K = {"combined": 16, "z": 12, "mcd": 4}


def f(v, nd=4):
    return "n/a" if v is None else f"{v:.{nd}f}"


def main() -> None:
    cal = {n: json.load(open(D / f"calibration_n{n}.json")) for n in SIZES}
    gn = json.load(open(D / "gaussian_null.json"))
    L = ["# V1 calibration diagnostic (generated by scripts/adoption_calibration_summary.py; do not hand-edit)", "",
         "Clean lots (baseline family, defect prevalence 0, seed 7101) through `fusion.run_full_pipeline`, "
         "`MODULE_A_SCORING=absolute`. 100 lots for n <= 40, 40 lots above.", "",
         "## 1. Part-level share of clean parts at or above REVIEW (s >= 2.956, p <= 1.1e-3)", "",
         "| n | lots | parts | combined (pipeline tier) | z leg alone | MCD leg alone |", "|---|---|---|---|---|---|"]
    for n in SIZES:
        r = cal[n]["part_level_share_at_or_above_REVIEW_s2.956"]
        L.append(f"| {n} | {cal[n]['lots']} | {cal[n]['parts']} | {f(r['combined_pipeline_tier'])} | {f(r['z_leg_alone'])} | {f(r['mcd_leg_alone'])} |")
    L += ["", "## 2. Calibration histogram: share of individual scores with p below t (nominal = t)", "",
          "z scores: every |robust z| of every frame and checkpoint (12 per part). MCD scores: every per-checkpoint distance "
          "(4 per part), refitted as `compute_lot_raw` fits them. The last two columns repeat the same shares on pure "
          "Gaussian data (`gaussian_null.json`, 1000 simulated lots per n, same estimator).", "",
          "| n | leg | p<1e-2 | p<1e-3 | p<1e-4 | ratio at 1e-3 (observed / nominal) | Gaussian-null p<1e-3 | Gaussian-null ratio |",
          "|---|---|---|---|---|---|---|---|"]
    for n in SIZES:
        for leg in ("z", "mcd"):
            p = cal[n]["per_score_share_p_below"]
            if p["0.01"][leg] is None:
                continue
            g = gn[str(n)].get(leg)
            L.append(f"| {n} | {leg} | {f(p['0.01'][leg], 5)} | {f(p['0.001'][leg], 5)} | {f(p['0.0001'][leg], 5)} | "
                     f"{p['0.001'][leg] / 1e-3:.1f}x | {f(g['0.001'], 5) if g else 'n/a'} | {f(g['0.001'] / 1e-3, 1) + 'x' if g else 'n/a'} |")
    L += ["", "## 3. Part-level share (max over the part's scores) with p below t, by leg", "",
          "| n | leg | K | p<1e-2 | p<1e-3 | p<1e-4 | nominal if K scores were independent: 1-(1-t)^K at 1e-2 / 1e-3 / 1e-4 |", "|---|---|---|---|---|---|---|"]
    for n in SIZES:
        for leg, key in (("combined", "combined"), ("z", "z_leg"), ("mcd", "mcd_leg")):
            pl = cal[n]["part_level_share_p_below"]
            if pl["0.01"][key] is None:
                continue
            k = K[leg] if (leg != "combined" or n >= 30) else 12
            if leg == "mcd" and n < 30:
                continue
            nom = " / ".join(f"{1 - (1 - t) ** k:.4f}" for t in (1e-2, 1e-3, 1e-4))
            c1 = "n/v" if leg == "combined" else f(pl['0.01'][key])
            L.append(f"| {n} | {leg} | {k} | {c1} | {f(pl['0.001'][key])} | {f(pl['0.0001'][key])} | {nom} |")
    L += ["", "n/v = not valid: for a part that is not flagged, the pipeline stores the Module A result of its FIRST parameter, "
          "not its maximum-severity frame (fusion/pipeline.py, `worst_parameter` for PASS parts), so the combined share is exact only "
          "at or above the REVIEW threshold (s >= 2.956, i.e. the 1e-3 and 1e-4 columns and section 1), not at p < 1e-2."]
    (D / "calibration_summary.md").write_text("\n".join(L) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
